# Generated by Django 5.2.7 on 2025-10-08 14:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockpricehistory',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Stock price history'},
        ),
        migrations.AlterModelOptions(
            name='userportfolio',
            options={'verbose_name_plural': 'User portfolios'},
        ),
        migrations.AddField(
            model_name='userportfolio',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
