# Generated by Django 5.2.7 on 2025-10-23 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_alter_transaction_user_alter_userbalance_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
