# Generated by Django 5.2.7 on 2025-10-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretmetadata',
            name='ttl_hours',
            field=models.IntegerField(default=24),
        ),
    ]
