# Generated by Django 4.2.24 on 2025-10-20 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('NormalUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='id_new_user', to='NormalUser.normaluser')),
                ('user_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_user', to='NormalUser.normaluser')),
            ],
        ),
    ]
