# SonarQube project configuration file
sonar.projectKey=backend-holy
sonar.projectName=Backend Holy
sonar.projectVersion=1.0

# Project source directories
sonar.sources=adminUser,backend,gift,NormalUser,stocks,Transaction,user_try,userActiveAndDesactive

sonar.language=py
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/venv/**, **/__pycache__/**, **/*.pyc, **/*.env

sonar.tests=adminUser,backend,gift,NormalUser,stocks,Transaction,user_try,userActiveAndDesactive
sonar.test.inclusions=**/tests.py,**/*_test.py
