"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6u4!9j7raq0&$y8z6j0^_(gi=o%$fezw=ym12u!vrcmpe&g=-s'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework",
    'user_try',
    'NormalUser',  
    'Transaction',
    'adminUser', 
    'gift',
    'userActiveAndDesactive',
    'stocks',  # NUEVA APP -
    'corsheaders',
]

# FINNHUB Data API Configuration
FINNHUB_API_KEY = 'd3ikvd9r01qmn7fki4o0d3ikvd9r01qmn7fki4og'  # FINNHUB API KEY - FREE TIER 

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'mydb',
        'USER': 'root',
        'PASSWORD': 'JmF120365+',  # USA TU PASSWORD LOCAL
        'HOST': 'localhost',   
        'PORT': '3306',
    }
}

# JWT Configuration
JWT_SECRET = 'your-very-secure-secret-key-change-in-production-2024'
JWT_ALGORITHM = 'HS256'

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'user_try.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',  # authenticated by default
    ],
}

# Auth0 Configuration
AUTH0_CONFIG = {
    'DOMAIN': 'dev-4qv4bs5w32upxtt5.us.auth0.com',  # Replace with your Auth0 domain
    'CLIENT_ID': 'A343FOgq0hloSROFvzxoXvN2JDMqaTa2',      # Replace with your Auth0 client ID
    'CLIENT_SECRET': '9Bu7e_4RCpoqpsnz-6PgRVBPPDOV-kvkQjPodlxA4uRfkBwbBBKW1cOHYQqZTcMj', # Replace with your Auth0 client secret
    'API_AUDIENCE': 'https://dev-4qv4bs5w32upxtt5.us.auth0.com/api/v2/',   # Optional: Your API audience
    'ALGORITHMS': ['RS256'],
}

# Django REST Framework Configuration - REPLACE existing
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'user_try.auth.Auth0Authentication',  # Primary authentication
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# Optional: Allow public access to specific views
# We'll handle this with @permission_classes([AllowAny]) in views

# Configure these for email (not implemented yet)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # this line is for development
EMAIL_HOST = 'smtp.example.com'
EMAIL_PORT = None
EMAIL_USE_TLS = True
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''

DEFAULT_FROM_EMAIL = 'noreply@stocktrading.com'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # Puerto de Vite
    "http://localhost:3000",
]
CORS_ALLOW_CREDENTIALS = True
