# Generated by Django 4.2.24 on 2025-10-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_try', '0002_user_created_at_user_ip_address_user_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='referral_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='referred_by',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='type',
        ),
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
