# Generated by Django 4.2.24 on 2025-10-16 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_try', '0003_remove_user_referral_code_remove_user_referred_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('suspended', 'Suspended')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('standard', 'Standard'), ('admin', 'Admin'), ('vip', 'VIP')], default='standard', max_length=50),
        ),
    ]
